version: '3.7'
services:
    db:
        image: mariadb:latest
        command: "mysqld --max_allowed_packet=110M"
        container_name: mariadb
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"

    app:
        build: "."
        depends_on:
            - db
        container_name: backend
        restart: always
        volumes:
            - storage:/var/lib/spotify_clone
        ports:
            - 15000:15000
        environment:
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_HOST: mariadb

    frontend:
        image: frontend
        container_name: frontend
        ports:
            - 80:3000
        depends_on:
            - app

volumes:
    storage: